---
roles:
  base:
    private_networks:
      - ip: '0.0.0.0'
        auto_network: true
    provisioners:
      - type: shell
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts

  master:
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 4096]
        - [modifyvm, !ruby/sym id, '--ioapic', 'on']
        - [modifyvm, !ruby/sym id, '--cpus', '4']
    synced_folders:
      - host_path:  '.files'
        guest_path: '/var/seteam-files'
    provisioners:
      - type: pe_bootstrap
        role: !ruby/sym master
        autosign:
          - jenkins.inf.puppetlabs.demo
          - wordpress.pdx.puppetlabs.demo
          - wordpress-staging.pdx.puppetlabs.demo
      - type: shell
        inline: |-
          /bin/bash /vagrant/scripts/deploy.sh
      - type: shell
        path: provision/bootstrap_puppet_master.sh
      - type: shell
        path: provision/set_server_role.sh
        args: 'role::puppet::master'

  posix_agent:
    provisioners:
      - type: shell
        inline: |-
          curl -sk https://master.inf.puppetlabs.demo:8140/packages/current/install.bash | /bin/bash 
      - type: shell
        inline: 'iptables -F'

  jenkins_master:
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 1024]
        - [modifyvm, !ruby/sym id, '--ioapic', 'on']
        - [modifyvm, !ruby/sym id, '--cpus', '2']
    provisioners:
      - type: shell
        path: provision/set_server_role.sh
        args:
          - '-w'
          - 'role::jenkins::master'
